<?php  $_cards = $this->getTotal()->getSnapCards(); ?>
<?php  $data = $this->getTotal()->getData(); ?>
<?php if ($this->getTotal()->getValue()): ?>
<?php foreach ($_cards as $_card): ?>
    <tr>
        <td colspan="<?php echo $this->getColspan(); ?>" style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right">
            <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?><strong><?php endif; ?>
                <?php $_title = $this->__('Remove'); ?>
                <?php $_url = Mage::getUrl('clutch/index/removeGc', array('code'=>$_card['card_number'])); ?>
                <a style="display: inline;" href="<?php echo $_url; ?>" title="<?php echo $_title; ?>"><img src="<?php echo $this->getSkinUrl('images/snap/btn_remove.gif') ?>" alt="<?php echo $this->__('Remove')?>" style="display:inline-block" /></a>

                <?php echo $this->__('Gift Card (%s)', $_card['card_number']); ?>
            <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?></strong><?php endif; ?>
        </td>
        <td style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right">
            <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?><strong><?php endif; ?>
                -<?php echo $this->helper('checkout')->formatPrice($_card['a']) ?>
            <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?></strong><?php endif; ?>
        </td>
    </tr>
<?php endforeach; ?>
<?php endif; ?>
