<li class="control" id="is_enrolled_loyalty_block" <?php if(Mage::getModel('checkout/cart')->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_GUEST): ?> style="display:none;" <?php endif; ?> >
    <div class="input-box">
        <input type="checkbox" name="is_enrolled_loyalty" title="<?php echo $this->__('Enroll to Loyalty Program') ?>" value="1" id="is_enrolled_loyalty" <?php if(Mage::getModel('checkout/cart')->getQuote()->getCheckoutMethod()!=Mage_Checkout_Model_Type_Onepage::METHOD_GUEST): ?> checked="checked" <?php endif; ?> class="checkbox" />
    </div>
    <label for="is_enrolled_loyalty"><?php echo $this->__('Enroll to '.Mage::getStoreConfig('general/store_information/name').' Loyalty Program') ?></label>
</li>
