<li class="control">
    <div class="input-box">
        <input type="checkbox" name="is_enrolled_loyalty" title="<?php echo $this->__('Enroll to Loyalty Program') ?>" value="1" id="is_enrolled_loyalty" checked="checked" class="checkbox" />
    </div>
    <label for="is_enrolled_loyalty"><?php echo $this->__('Enroll to '.Mage::getStoreConfig('general/store_information/name').' Loyalty Program') ?></label>
</li>
